### ISSUE TITLE
Code is compiling but  not running

### ISSUE THREAD

**Issue by MonaJoshi** [intesar-gist/floyd_warshall_openmp#1]
to Run: ./floyd_warshal_openmp test_data_1000.dat 4
This error is shown:
../test_data/test_data_1000.dat
==> Cannot proceed, unable to find data file ..

**Comment by intesar-gist** [comment]
@MonaJoshi the data file is missing as per the error. Please make sure you have downloaded data files and have put them in correct path.

FYI: Datafiles are also in the same repository under **test_data** folder

**Comment by MonaJoshi** [comment]
Yes I have downloaded the whole folder nd all files are intact therein.
Data files are the one with .dat extension..? All these files are present
still code is not running.

**Comment by intesar-gist** [comment]
Yes, .dat are the data files. You need to check file paths in the program then. May be code is unable to access the folder so make sure data files are accessible.

**Comment by MonaJoshi** [comment]
Actually data files were within the folder nd I copied them outside in the
same folder where there is the file containing the code. So I didn't gave
any path just gave the .dat filename. Still it's not running

**Comment by intesar-gist** [comment]
Yeah I know data files are in same folder. But sometimes file paths makes issue and it varies machine to machine or may be OS. For me `#define DATA_FOLDER  "../test_data/"` worked fine on Win10. You can play with this constant to set path on your machine.
